### ISSUE TITLE
删除事件后事件还在，点击后崩溃

### ISSUE THREAD

**Issue by pingplug** [maxiee/HeartBeat#11]
崩溃报告：
Android Version: 5.1.1
Device Model: Moto G 2014 LTE
Device Manufacturer: motorola
App Version: 0.9.5 (29)

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.maxiee.heartbeat/com.maxiee.heartbeat.ui.EventDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.maxiee.heartbeat.model.Event.getTimestamp()' on a null object reference
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.maxiee.heartbeat/com.maxiee.heartbeat.ui.EventDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.maxiee.heartbeat.model.Event.getTimestamp()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
    at android.app.ActivityThread.access$900(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5294)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.maxiee.heartbeat.model.Event.getTimestamp()' on a null object reference
    at com.maxiee.heartbeat.ui.EventDetailActivity.onCreate(EventDetailActivity.java:124)
    at android.app.Activity.performCreate(Activity.java:5990)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
    ... 11 more

ps：崩溃报告页面不能滚动😂

**Comment by maxiee** [comment]
我想了解一下更详细的信息。

请问你的删除操作是在哪个界面进行的？另外，按照同样的操作，是否还能复现这个崩溃问题？

感谢反馈～崩溃页面滚动会记得加上……囧rz

**Comment by pingplug** [comment]
在事件列表里面操作的
之后的尝试都不能复现这个问题

**Comment by maxiee** [comment]
看来是一个概率发生的 Bug 啊……😰

**Comment by pingplug** [comment]
今天新建事件后界面没有显示最新的事件，不会是界面没有及时刷新？

**Comment by maxiee** [comment]
按理说不应该，事件存在一个单例里面，每次从添加页面返回都会更新界面。

可能是我这块的实现还是有问题额……目前考虑用响应式框架 Agera 重构这块，自己维护太麻烦了。
